// Website generator with multiple templates
export function generateWebsite(prompt) {
  const lower = prompt.toLowerCase();
  const nameMatch = prompt.match(/for\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)/);
  const name = nameMatch ? nameMatch[1] : 'Your Business';
  
  let colors = { p: '#667eea', s: '#764ba2', a: '#f093fb' };
  if (lower.includes('blue')) colors = { p: '#4facfe', s: '#00f2fe', a: '#43e97b' };
  else if (lower.includes('green')) colors = { p: '#11998e', s: '#38ef7d', a: '#a8edea' };
  else if (lower.includes('red')) colors = { p: '#eb3349', s: '#f45c43', a: '#fa709a' };
  
  if (lower.includes('portfolio')) return genPortfolio(name, colors);
  if (lower.includes('restaurant') || lower.includes('cafe')) return genRestaurant(name, colors);
  if (lower.includes('shop') || lower.includes('store')) return genShop(name, colors);
  if (lower.includes('gym') || lower.includes('fitness')) return genFitness(name, colors);
  if (lower.includes('landing') || lower.includes('saas')) return genLanding(name, colors);
  return genGeneric(name, colors, prompt);
}

function genPortfolio(n, c) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif}@keyframes f{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}@keyframes g{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}.hero{background:linear-gradient(-45deg,${c.p},${c.s},${c.a},${c.p});background-size:400% 400%;animation:g 15s ease infinite;color:#fff;padding:150px 20px;text-align:center}.hero h1{font-size:4em;margin-bottom:20px;animation:f 1s}.hero p{font-size:1.5em;animation:f 1s .2s backwards}.sec{padding:80px 20px;max-width:1200px;margin:0 auto}.sec h2{text-align:center;font-size:2.5em;margin-bottom:50px;color:${c.p}}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:30px}.card{background:#f5f5f5;padding:40px;border-radius:15px;transition:all .3s;animation:f 1s backwards}.card:hover{transform:translateY(-10px);box-shadow:0 20px 40px rgba(0,0,0,.2)}.card h3{font-size:1.5em;margin-bottom:15px}.contact{background:linear-gradient(135deg,${c.p},${c.s});color:#fff;padding:80px 20px;text-align:center}.btn{display:inline-block;padding:15px 40px;background:#fff;color:${c.p};text-decoration:none;border-radius:50px;font-weight:bold;margin-top:20px;transition:all .3s}.btn:hover{transform:translateY(-3px);box-shadow:0 10px 30px rgba(0,0,0,.3)}</style></head><body><div class="hero"><h1>${n}</h1><p>Full Stack Developer & Designer</p></div><div class="sec"><h2>Projects</h2><div class="grid"><div class="card"><h3>🚀 E-Commerce</h3><p>Modern shopping platform</p></div><div class="card"><h3>📱 Task Manager</h3><p>Productivity application</p></div><div class="card"><h3>🌤️ Weather App</h3><p>Real-time weather data</p></div></div></div><div class="contact"><h2>Let's Work Together</h2><a href="#" class="btn">Contact Me</a></div></body></html>`;
}

function genRestaurant(n, c) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Georgia,serif}@keyframes f{from{opacity:0}to{opacity:1}}@keyframes s{from{opacity:0;transform:translateX(-30px)}to{opacity:1;transform:translateX(0)}}.header{background:linear-gradient(135deg,#2c1810,#4a2c1a);color:#f4e4c1;padding:20px;text-align:center;position:sticky;top:0;z-index:100}.hero{background:linear-gradient(rgba(0,0,0,.6),rgba(0,0,0,.6)),linear-gradient(135deg,#654321,#8b4513);color:#fff;padding:180px 20px;text-align:center}.hero h1{font-size:5em;margin-bottom:20px;animation:s 1s}.hero p{font-size:1.8em;animation:s 1s .3s backwards}.menu{padding:80px 20px;max-width:1000px;margin:0 auto}.menu h2{text-align:center;margin-bottom:50px;font-size:3em;color:#2c1810}.items{display:grid;gap:30px}.item{display:flex;justify-content:space-between;padding:25px;background:#fff;border-radius:10px;transition:all .3s;animation:s .8s backwards}.item:hover{transform:translateX(10px);box-shadow:0 5px 20px rgba(193,120,23,.2)}.item h3{color:#2c1810;font-size:1.5em}.price{color:#c17817;font-weight:bold;font-size:1.5em}.footer{background:linear-gradient(135deg,#2c1810,#1a0f08);color:#f4e4c1;padding:60px 20px;text-align:center}</style></head><body><div class="header"><h2>☕ ${n.toUpperCase()}</h2></div><div class="hero"><h1>Welcome</h1><p>Fresh coffee & pastries</p></div><div class="menu"><h2>Our Menu</h2><div class="items"><div class="item"><div><h3>Espresso</h3><p>Rich Italian coffee</p></div><span class="price">$3.50</span></div><div class="item"><div><h3>Cappuccino</h3><p>Steamed milk foam</p></div><span class="price">$4.50</span></div><div class="item"><div><h3>Croissant</h3><p>Buttery pastry</p></div><span class="price">$3.00</span></div></div></div><div class="footer"><h3>Visit Us</h3><p>📍 123 Main St | 🕐 7AM-8PM | 📞 (555) 123-4567</p></div></body></html>`;
}

function genShop(n, c) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif}@keyframes f{from{opacity:0}to{opacity:1}}.nav{background:#fff;padding:20px 40px;box-shadow:0 2px 10px rgba(0,0,0,.1);display:flex;justify-content:space-between;position:sticky;top:0;z-index:100}.logo{font-size:1.8em;font-weight:bold;background:linear-gradient(135deg,${c.p},${c.s});-webkit-background-clip:text;-webkit-text-fill-color:transparent}.cart{padding:10px 25px;background:linear-gradient(135deg,${c.p},${c.s});color:#fff;border:none;border-radius:25px;cursor:pointer}.hero{background:linear-gradient(135deg,${c.p},${c.s});color:#fff;padding:100px 20px;text-align:center}.hero h1{font-size:4em;margin-bottom:20px}.products{max-width:1400px;margin:80px auto;padding:0 20px}.products h2{text-align:center;font-size:3em;margin-bottom:60px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:40px}.pcard{background:#fff;border-radius:15px;overflow:hidden;box-shadow:0 5px 20px rgba(0,0,0,.1);transition:all .4s;animation:f 1s backwards}.pcard:hover{transform:translateY(-10px);box-shadow:0 15px 40px rgba(0,0,0,.2)}.pimg{height:250px;background:linear-gradient(135deg,#f5f7fa,#c3cfe2);display:flex;align-items:center;justify-content:center;font-size:5em}.pinfo{padding:25px}.pname{font-size:1.4em;margin-bottom:10px}.pprice{font-size:1.8em;color:${c.p};font-weight:bold;margin-bottom:15px}.pbtn{width:100%;padding:12px;background:linear-gradient(135deg,${c.p},${c.s});color:#fff;border:none;border-radius:8px;cursor:pointer;font-weight:600}.pbtn:hover{transform:translateY(-2px)}</style></head><body><nav class="nav"><div class="logo">🛍️ ${n}</div><button class="cart">🛒 Cart (0)</button></nav><div class="hero"><h1>Welcome to Our Store</h1><p style="font-size:1.5em">Amazing products at great prices</p></div><div class="products"><h2>Featured Products</h2><div class="grid"><div class="pcard"><div class="pimg">👕</div><div class="pinfo"><div class="pname">Premium T-Shirt</div><div class="pprice">$29.99</div><button class="pbtn">Add to Cart</button></div></div><div class="pcard"><div class="pimg">👟</div><div class="pinfo"><div class="pname">Running Shoes</div><div class="pprice">$79.99</div><button class="pbtn">Add to Cart</button></div></div><div class="pcard"><div class="pimg">🎧</div><div class="pinfo"><div class="pname">Headphones</div><div class="pprice">$149.99</div><button class="pbtn">Add to Cart</button></div></div><div class="pcard"><div class="pimg">⌚</div><div class="pinfo"><div class="pname">Smart Watch</div><div class="pprice">$199.99</div><button class="pbtn">Add to Cart</button></div></div></div></div></body></html>`;
}

function genFitness(n, c) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif}@keyframes p{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}.hero{background:linear-gradient(rgba(0,0,0,.5),rgba(0,0,0,.5)),linear-gradient(135deg,${c.p},${c.s});height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;color:#fff}.hero h1{font-size:5em;margin-bottom:20px;animation:p 2s ease-in-out infinite}.hero p{font-size:2em}.cta{display:inline-block;margin-top:30px;padding:20px 50px;background:${c.a};color:#fff;text-decoration:none;border-radius:50px;font-weight:bold;font-size:1.2em;transition:all .3s}.cta:hover{transform:scale(1.1);box-shadow:0 10px 30px rgba(0,0,0,.3)}.programs{padding:100px 20px;max-width:1200px;margin:0 auto}.programs h2{font-size:3em;text-align:center;margin-bottom:60px}.pgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:40px}.pcard{background:linear-gradient(135deg,${c.p},${c.s});color:#fff;padding:40px;border-radius:15px;transition:transform .3s}.pcard:hover{transform:translateY(-10px)}.pcard h3{font-size:2em;margin-bottom:15px}</style></head><body><div class="hero"><div><h1>💪 ${n}</h1><p>Transform Your Body, Transform Your Life</p><a href="#" class="cta">Start Your Journey</a></div></div><div class="programs"><h2>Our Programs</h2><div class="pgrid"><div class="pcard"><h3>🏋️ Strength Training</h3><p>Build muscle with expert trainers</p></div><div class="pcard"><h3>🧘 Yoga Classes</h3><p>Find balance and flexibility</p></div><div class="pcard"><h3>🏃 Cardio Workouts</h3><p>Boost endurance effectively</p></div></div></div></body></html>`;
}

function genLanding(n, c) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif}@keyframes f{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}.hero{background:linear-gradient(135deg,${c.p},${c.s},${c.a});color:#fff;padding:140px 20px;text-align:center}.hero h1{font-size:4em;margin-bottom:20px;animation:f 1s}.hero p{font-size:1.5em;margin-bottom:30px;animation:f 1s .2s backwards}.cta{display:inline-block;padding:18px 50px;background:#fff;color:${c.p};text-decoration:none;border-radius:50px;font-weight:bold;font-size:1.2em;transition:all .3s;animation:f 1s .4s backwards}.cta:hover{transform:translateY(-5px) scale(1.05);box-shadow:0 15px 40px rgba(0,0,0,.4)}.features{padding:100px 20px;max-width:1200px;margin:0 auto}.features h2{text-align:center;font-size:3em;margin-bottom:70px;background:linear-gradient(135deg,${c.p},${c.s});-webkit-background-clip:text;-webkit-text-fill-color:transparent}.fgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:50px}.feature{text-align:center;padding:40px;background:#fff;border-radius:20px;transition:all .4s;box-shadow:0 5px 20px rgba(0,0,0,.05)}.feature:hover{transform:translateY(-10px);box-shadow:0 15px 40px rgba(0,0,0,.15)}.ficon{font-size:4em;margin-bottom:25px}.feature h3{margin-bottom:15px;font-size:1.5em}.cta-sec{background:linear-gradient(135deg,${c.p},${c.s});padding:100px 20px;text-align:center;color:#fff}.cta-sec h2{font-size:3em;margin-bottom:20px}.cta-sec p{font-size:1.3em;margin-bottom:40px}</style></head><body><div class="hero"><h1>Build Your Dream Product</h1><p>The all-in-one platform for modern teams</p><a href="#" class="cta">Get Started Free →</a></div><div class="features"><h2>Why Choose Us</h2><div class="fgrid"><div class="feature"><div class="ficon">⚡</div><h3>Lightning Fast</h3><p>Optimized performance for best experience</p></div><div class="feature"><div class="ficon">🔒</div><h3>Secure</h3><p>Enterprise-grade security</p></div><div class="feature"><div class="ficon">🎨</div><h3>Customizable</h3><p>Tailor everything to your brand</p></div></div></div><div class="cta-sec"><h2>Ready to Get Started?</h2><p>Join thousands of satisfied customers</p><a href="#" class="cta">Start Your Free Trial</a></div></body></html>`;
}
function
 genGeneric(n, c, prompt) {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${n}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif}@keyframes f{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}@keyframes g{0%,100%{background-position:0% 50%}50%{background-position:100% 50%}}.header{background:linear-gradient(-45deg,${c.p},${c.s},${c.a},${c.p});background-size:400% 400%;animation:g 15s ease infinite;color:#fff;padding:100px 20px;text-align:center}.header h1{font-size:4em;margin-bottom:15px;animation:f 1s}.header p{font-size:1.3em;animation:f 1s .2s backwards}.content{max-width:1200px;margin:80px auto;padding:0 20px}.section{margin-bottom:80px;animation:f 1s backwards}.section h2{font-size:2.5em;margin-bottom:25px;background:linear-gradient(135deg,${c.p},${c.s});-webkit-background-clip:text;-webkit-text-fill-color:transparent}.section p{color:#666;font-size:1.15em;margin-bottom:15px;line-height:1.8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:35px;margin-top:50px}.card{background:linear-gradient(135deg,#f5f7fa,#c3cfe2);padding:35px;border-radius:15px;transition:all .4s;animation:f 1s backwards;cursor:pointer}.card:hover{transform:translateY(-10px) scale(1.02);box-shadow:0 20px 40px rgba(0,0,0,.2)}.card h3{margin-bottom:15px;font-size:1.5em}.footer{background:linear-gradient(135deg,${c.p},${c.s});color:#fff;padding:60px 20px;text-align:center;margin-top:80px}.info{background:rgba(102,126,234,.1);border-left:4px solid ${c.p};padding:20px;margin:30px 0;border-radius:5px}.info strong{color:${c.p}}</style></head><body><div class="header"><h1>Welcome</h1><p>Your custom website generated by AI</p></div><div class="content"><div class="section"><h2>About This Website</h2><div class="info"><strong>Your Prompt:</strong> "${prompt}"</div><p>This website was automatically generated based on your description with modern design and smooth animations.</p></div><div class="section"><h2>Key Features</h2><div class="grid"><div class="card"><h3>🚀 Feature One</h3><p>Description of your first key feature</p></div><div class="card"><h3>💡 Feature Two</h3><p>Description of your second key feature</p></div><div class="card"><h3>⭐ Feature Three</h3><p>Description of your third key feature</p></div></div></div></div><div class="footer"><p>&copy; 2026 ${n}. All rights reserved.</p><p style="margin-top:10px;font-size:.9em">Built with AI Website Builder</p></div></body></html>`;
}
